apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubeconfigs.kubebrowser.io
spec:
  group: kubebrowser.io
  names:
    kind: Kubeconfig
    listKind: KubeconfigList
    plural: kubeconfigs
    singular: kubeconfig
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            metadata:
              type: object
            spec:
              type: object
              required:
                - name
                - kubeconfig
              properties:
                name:
                  type: string
                kubeconfig:
                  type: object
                  required:
                    - apiVersion
                    - kind
                    - clusters
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    clusters:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          cluster:
                            type: object
                            properties:
                              server:
                                type: string
                              certificate-authority-data:
                                type: string
                                nullable: true
                              insecure-skip-tls-verify:
                                type: boolean
                    contexts:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          context:
                            type: object
                            properties:
                              cluster:
                                type: string
                              user:
                                type: string
                    current-context:
                      type: string
                      nullable: true
                whitelist:
                  type: object
                  properties:
                    users:
                      type: array
                      items:
                        type: string
                    groups:
                      type: array
                      items:
                        type: string
