apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: kubebrowser
build:
  artifacts:
    - image: backend
      context: server
      # buildpacks:
      #   builder: gcr.io/buildpacks/builder:v1
      ko: {}
  # local:
  #   push: true
manifests:
  rawYaml:
    - k8s/*yaml
portForward:
  - resourceType: deployment
    resourceName: backend
    namespace: default
    port: 8080
