{{- /*
Author: Yann Lacroix <yann.lacroix@avisto.com>
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubebrowser.server.kubeconfigsName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: server
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
{{- if not .Values.server.kubeconfigs }}
  kubeconfig: |
    {
      "name": "No Kubeconfig Yet",
      "content": {
        "apiVersion": "v1",
        "clusters": [
          {
            "cluster": {
              "certificate-authority-data": "xxx",
              "server": "xxx"
            },
            "name": "clusterA"
          }
        ],
        "contexts": [
          {
            "context": {
              "cluster": "clusterA",
              "namespace": "namespaceA",
              "user": "oidc"
            },
            "name": "contextA"
          }
        ],
        "current-context": "contextA",
        "kind": "Config",
        "preferences": {}
      }
    }

{{- else }}
{{- range $value := .Values.server.kubeconfigs }}
  {{ $value.name | kebabcase }}: |
    {
      "name": "{{ $value.name }}",
      "content": {{ mustToJson $value.kubeconfig }}
    }
{{- end }}
{{- end }}
