apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: server-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: server
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: server-clusterrole
  apiGroup: rbac.authorization.k8s.io
