{{- /*
Author: Yann Lacroix <yann.lacroix@avisto.com>
*/}}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.names.fullname" . }}-rolebinding
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.secretAnnotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.server.serviceAccountName | quote }}
    namespace: {{ include "common.names.namespace" . | quote }}
roleRef:
  kind: Role
  name: {{ include "common.names.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
