{{- /*
Author: Yann Lacroix <yann.lacroix@avisto.com>
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-oauth2
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.secretAnnotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  clientID: {{ .Values.server.oidc.clientID | b64enc | quote}}
  clientSecret: {{ .Values.server.oidc.clientSecret | b64enc | quote}}
  issuerURL: {{ .Values.server.oidc.issuerURL | b64enc | quote}}
