/*
Copyright Yann Lacroix.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AuthProviderSpecApplyConfiguration represents a declarative configuration of the AuthProviderSpec type for use
// with apply.
type AuthProviderSpecApplyConfiguration struct {
	Name   *string                               `json:"name,omitempty"`
	Config *AuthProviderConfigApplyConfiguration `json:"config,omitempty"`
}

// AuthProviderSpecApplyConfiguration constructs a declarative configuration of the AuthProviderSpec type for use with
// apply.
func AuthProviderSpec() *AuthProviderSpecApplyConfiguration {
	return &AuthProviderSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AuthProviderSpecApplyConfiguration) WithName(value string) *AuthProviderSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithConfig sets the Config field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Config field is set to the value of the last call.
func (b *AuthProviderSpecApplyConfiguration) WithConfig(value *AuthProviderConfigApplyConfiguration) *AuthProviderSpecApplyConfiguration {
	b.Config = value
	return b
}
