/*
Copyright Yann Lacroix.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// KubeconfigDataApplyConfiguration represents a declarative configuration of the KubeconfigData type for use
// with apply.
type KubeconfigDataApplyConfiguration struct {
	APIVersion     *string                     `json:"apiVersion,omitempty"`
	Kind           *string                     `json:"kind,omitempty"`
	Clusters       []ClusterApplyConfiguration `json:"clusters,omitempty"`
	Contexts       []ContextApplyConfiguration `json:"contexts,omitempty"`
	CurrentContext *string                     `json:"current-context,omitempty"`
	Users          []UserApplyConfiguration    `json:"users,omitempty"`
}

// KubeconfigDataApplyConfiguration constructs a declarative configuration of the KubeconfigData type for use with
// apply.
func KubeconfigData() *KubeconfigDataApplyConfiguration {
	return &KubeconfigDataApplyConfiguration{}
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *KubeconfigDataApplyConfiguration) WithAPIVersion(value string) *KubeconfigDataApplyConfiguration {
	b.APIVersion = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *KubeconfigDataApplyConfiguration) WithKind(value string) *KubeconfigDataApplyConfiguration {
	b.Kind = &value
	return b
}

// WithClusters adds the given value to the Clusters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Clusters field.
func (b *KubeconfigDataApplyConfiguration) WithClusters(values ...*ClusterApplyConfiguration) *KubeconfigDataApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithClusters")
		}
		b.Clusters = append(b.Clusters, *values[i])
	}
	return b
}

// WithContexts adds the given value to the Contexts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Contexts field.
func (b *KubeconfigDataApplyConfiguration) WithContexts(values ...*ContextApplyConfiguration) *KubeconfigDataApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithContexts")
		}
		b.Contexts = append(b.Contexts, *values[i])
	}
	return b
}

// WithCurrentContext sets the CurrentContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentContext field is set to the value of the last call.
func (b *KubeconfigDataApplyConfiguration) WithCurrentContext(value string) *KubeconfigDataApplyConfiguration {
	b.CurrentContext = &value
	return b
}

// WithUsers adds the given value to the Users field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Users field.
func (b *KubeconfigDataApplyConfiguration) WithUsers(values ...*UserApplyConfiguration) *KubeconfigDataApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithUsers")
		}
		b.Users = append(b.Users, *values[i])
	}
	return b
}
