apiVersion: kubebrowser.io/v1
kind: Kubeconfig
metadata:
  name: example-kubeconfig4
  namespace: default
spec:
  name: Another cluster
  kubeconfig:
    apiVersion: v1
    kind: Config
    clusters:
      - name: another-cluster
        cluster:
          server: https://example-cluster.example.com
          certificate-authority-data: "base64-encoded-ca-cert"
    contexts:
      - name: example-context
        context:
          cluster: example-cluster
          user: example-user
    current-context: example-context
