/*
Copyright Yann Lacroix.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	kubeconfigv1 "github.com/brawdunoir/kubebrowser/pkg/apis/kubeconfig/v1"
	applyconfigurationkubeconfigv1 "github.com/brawdunoir/kubebrowser/pkg/client/applyconfiguration/kubeconfig/v1"
	scheme "github.com/brawdunoir/kubebrowser/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// KubeconfigsGetter has a method to return a KubeconfigInterface.
// A group's client should implement this interface.
type KubeconfigsGetter interface {
	Kubeconfigs(namespace string) KubeconfigInterface
}

// KubeconfigInterface has methods to work with Kubeconfig resources.
type KubeconfigInterface interface {
	Create(ctx context.Context, kubeconfig *kubeconfigv1.Kubeconfig, opts metav1.CreateOptions) (*kubeconfigv1.Kubeconfig, error)
	Update(ctx context.Context, kubeconfig *kubeconfigv1.Kubeconfig, opts metav1.UpdateOptions) (*kubeconfigv1.Kubeconfig, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*kubeconfigv1.Kubeconfig, error)
	List(ctx context.Context, opts metav1.ListOptions) (*kubeconfigv1.KubeconfigList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *kubeconfigv1.Kubeconfig, err error)
	Apply(ctx context.Context, kubeconfig *applyconfigurationkubeconfigv1.KubeconfigApplyConfiguration, opts metav1.ApplyOptions) (result *kubeconfigv1.Kubeconfig, err error)
	KubeconfigExpansion
}

// kubeconfigs implements KubeconfigInterface
type kubeconfigs struct {
	*gentype.ClientWithListAndApply[*kubeconfigv1.Kubeconfig, *kubeconfigv1.KubeconfigList, *applyconfigurationkubeconfigv1.KubeconfigApplyConfiguration]
}

// newKubeconfigs returns a Kubeconfigs
func newKubeconfigs(c *KubeconfigV1Client, namespace string) *kubeconfigs {
	return &kubeconfigs{
		gentype.NewClientWithListAndApply[*kubeconfigv1.Kubeconfig, *kubeconfigv1.KubeconfigList, *applyconfigurationkubeconfigv1.KubeconfigApplyConfiguration](
			"kubeconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kubeconfigv1.Kubeconfig { return &kubeconfigv1.Kubeconfig{} },
			func() *kubeconfigv1.KubeconfigList { return &kubeconfigv1.KubeconfigList{} },
		),
	}
}
