/*
Copyright Yann Lacroix.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// KubeconfigSpecApplyConfiguration represents a declarative configuration of the KubeconfigSpec type for use
// with apply.
type KubeconfigSpecApplyConfiguration struct {
	Name       *string                           `json:"name,omitempty"`
	Kubeconfig *KubeconfigDataApplyConfiguration `json:"kubeconfig,omitempty"`
	Whitelist  *WhitelistApplyConfiguration      `json:"whitelist,omitempty"`
}

// KubeconfigSpecApplyConfiguration constructs a declarative configuration of the KubeconfigSpec type for use with
// apply.
func KubeconfigSpec() *KubeconfigSpecApplyConfiguration {
	return &KubeconfigSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *KubeconfigSpecApplyConfiguration) WithName(value string) *KubeconfigSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithKubeconfig sets the Kubeconfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kubeconfig field is set to the value of the last call.
func (b *KubeconfigSpecApplyConfiguration) WithKubeconfig(value *KubeconfigDataApplyConfiguration) *KubeconfigSpecApplyConfiguration {
	b.Kubeconfig = value
	return b
}

// WithWhitelist sets the Whitelist field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Whitelist field is set to the value of the last call.
func (b *KubeconfigSpecApplyConfiguration) WithWhitelist(value *WhitelistApplyConfiguration) *KubeconfigSpecApplyConfiguration {
	b.Whitelist = value
	return b
}
