/*
Copyright Yann Lacroix.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiskubeconfigv1alpha1 "github.com/AvistoTelecom/kubebrowser/pkg/apis/kubeconfig/v1alpha1"
	versioned "github.com/AvistoTelecom/kubebrowser/pkg/client/clientset/versioned"
	internalinterfaces "github.com/AvistoTelecom/kubebrowser/pkg/client/informers/externalversions/internalinterfaces"
	kubeconfigv1alpha1 "github.com/AvistoTelecom/kubebrowser/pkg/client/listers/kubeconfig/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KubeconfigInformer provides access to a shared informer and lister for
// Kubeconfigs.
type KubeconfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() kubeconfigv1alpha1.KubeconfigLister
}

type kubeconfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKubeconfigInformer constructs a new informer for Kubeconfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKubeconfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKubeconfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKubeconfigInformer constructs a new informer for Kubeconfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKubeconfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeconfigV1alpha1().Kubeconfigs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeconfigV1alpha1().Kubeconfigs(namespace).Watch(context.TODO(), options)
			},
		},
		&apiskubeconfigv1alpha1.Kubeconfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *kubeconfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKubeconfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kubeconfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiskubeconfigv1alpha1.Kubeconfig{}, f.defaultInformer)
}

func (f *kubeconfigInformer) Lister() kubeconfigv1alpha1.KubeconfigLister {
	return kubeconfigv1alpha1.NewKubeconfigLister(f.Informer().GetIndexer())
}
